# action.yml
name: Crawler
description: 'Crawl website to find orphan pages'
inputs:
  start-url:  # id of input
    description: 'Url to start crawling from'
    required: true
    default: "https://open-horizon.github.io/"
outputs:
  orphan-pages: # id of output
    description: 'Orphan pages found'
    # value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        echo "This is a bash shell"
        declare -a crawled_links
        echo "Link ${{ inputs.start-url }}."
        export LOG=log.txt
        export URL=${{ inputs.start-url }}
        wget --no-directories --mirror --spider "$URL" 2>&1 | tee "$LOG";
        crawled_links=(`grep -P -o -e '(?<=^--....-..-.. ..:..:..--  )(.*)' "$LOG"`);
        echo "::set-output name=orphan-pages::$crawled_links"
      shell: bash