# action.yml
name: Crawler
description: 'Crawl website to find orphan pages'
inputs:
  start-url:  # id of input
    description: 'Url to start crawling from'
    required: true
    default: "https://open-horizon.github.io/"
outputs:
  orphan-pages: # id of output
    description: 'Orphan pages found'
defaults:
  run:
    shell: bash
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.start-url }}