# action.yml
name: Crawler
description: 'Crawl website to find orphan pages'
inputs:
  start-url:  # id of input
    description: 'Url to start crawling from'
    required: true
    default: https://open-horizon.github.io
outputs:
  orphan-pages: # id of output
    description: 'Orphan pages found'
    # value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        echo "This is a bash shell"
        pwd
        echo "Link ${{ inputs.start-url }}."
        export LOG=/home/runner/work/orphan-pages-action-jekyll/orphan-pages-action-jekyll/log.txt
        export URL=${{ inputs.start-url }}
        echo $URL
        echo "before wget"
        wget -U mozilla -r --no-check-certificate --timeout=2 'https://open-horizon.github.io' >>/dev/null 2>&1 | tee log.txt;
        echo "after wget"
        echo $?;
        ls;
        cat ./log.txt
        echo "after cat"
        # cat $LOG;
        # # grep -P -o -e '(?<=^--....-..-.. ..:..:..--  )(.*)' "$LOG"
      shell: bash